/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica_2_4;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ixchel
 */
public class FlatLaf extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlatLaf.class.getName());

    /**
     * Creates new form FlatLaf
     */
    public FlatLaf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGrupoOpcionHidari = new javax.swing.ButtonGroup();
        jGrupoOpcionMigi = new javax.swing.ButtonGroup();
        hidari = new javax.swing.JPanel();
        Texto1Hidari = new javax.swing.JLabel();
        txtHidari1 = new javax.swing.JTextField();
        CorreoHidari = new javax.swing.JLabel();
        txtCorreoHidari = new javax.swing.JTextField();
        jContrasenyaHidari = new javax.swing.JLabel();
        txtPassHidari = new javax.swing.JPasswordField();
        jAceptarHidari = new javax.swing.JButton();
        jRedondoHidari2 = new javax.swing.JButton();
        jButtonAyudaHidari = new javax.swing.JButton();
        Opciones = new javax.swing.JLabel();
        jOpcion1 = new javax.swing.JRadioButton();
        jOpcion2 = new javax.swing.JRadioButton();
        jOpcion3 = new javax.swing.JRadioButton();
        jOpcion4 = new javax.swing.JCheckBox();
        jOpcion5 = new javax.swing.JCheckBox();
        jOpcion6 = new javax.swing.JCheckBox();
        jComboListHidari = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jDesliz = new javax.swing.JSlider();
        migi = new javax.swing.JPanel();
        Opciones1Migi = new javax.swing.JLabel();
        jOpcion1Migi = new javax.swing.JRadioButton();
        jOpcion2Migi = new javax.swing.JRadioButton();
        jOpcion3Migi = new javax.swing.JRadioButton();
        CorreoMigi = new javax.swing.JLabel();
        jContrasenyaMigi = new javax.swing.JLabel();
        txtPassMigi = new javax.swing.JPasswordField();
        txtCorreoMigi = new javax.swing.JTextField();
        jOpcion6Migi = new javax.swing.JCheckBox();
        jOpcion5Migi = new javax.swing.JCheckBox();
        jOpcion4Migi = new javax.swing.JCheckBox();
        txtMigi = new javax.swing.JTextField();
        Texto1Migi = new javax.swing.JLabel();
        jSpinnerMigi = new javax.swing.JSpinner();
        jComboListMigi = new javax.swing.JComboBox<>();
        jDeslizMigi = new javax.swing.JSlider();
        jAceptarMigi = new javax.swing.JButton();
        jRedondoMigi = new javax.swing.JButton();
        jButtonAyudaMigi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 700));

        hidari.setBorder(javax.swing.BorderFactory.createTitledBorder("GUI Mixta"));
        hidari.setLayout(new java.awt.GridBagLayout());

        Texto1Hidari.setText("Texto 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 27, 0, 0);
        hidari.add(Texto1Hidari, gridBagConstraints);

        txtHidari1.setColumns(20);
        txtHidari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHidari1ActionPerformed(evt);
            }
        });
        txtHidari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHidari1KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        hidari.add(txtHidari1, gridBagConstraints);

        CorreoHidari.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 60, 0, 0);
        hidari.add(CorreoHidari, gridBagConstraints);

        txtCorreoHidari.setColumns(20);
        txtCorreoHidari.setText("sunombre@gmail.com...");
        txtCorreoHidari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoHidariActionPerformed(evt);
            }
        });
        txtCorreoHidari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoHidariKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 1, 0, 0);
        hidari.add(txtCorreoHidari, gridBagConstraints);

        jContrasenyaHidari.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 60, 0, 0);
        hidari.add(jContrasenyaHidari, gridBagConstraints);

        txtPassHidari.setText("jPasswordField1");
        txtPassHidari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassHidariKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 0);
        hidari.add(txtPassHidari, gridBagConstraints);

        jAceptarHidari.setText("Aceptar");
        jAceptarHidari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarHidariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 32, 0, 0);
        hidari.add(jAceptarHidari, gridBagConstraints);

        jRedondoHidari2.setText("Redondo");
        jRedondoHidari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRedondoHidari2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 27, 0, 0);
        hidari.add(jRedondoHidari2, gridBagConstraints);

        jButtonAyudaHidari.setText("?");
        jButtonAyudaHidari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaHidariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 17, 0, 0);
        hidari.add(jButtonAyudaHidari, gridBagConstraints);

        Opciones.setText("Opciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 11, 0, 0);
        hidari.add(Opciones, gridBagConstraints);

        jGrupoOpcionHidari.add(jOpcion1);
        jOpcion1.setText("Opcion 1");
        jOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 0, 0);
        hidari.add(jOpcion1, gridBagConstraints);

        jGrupoOpcionHidari.add(jOpcion2);
        jOpcion2.setText("Opcion 2");
        jOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 60, 0, 0);
        hidari.add(jOpcion2, gridBagConstraints);

        jGrupoOpcionHidari.add(jOpcion3);
        jOpcion3.setText("Opcion 3");
        jOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 60, 0, 0);
        hidari.add(jOpcion3, gridBagConstraints);

        jOpcion4.setText("Opcion 4");
        jOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 43, 0, 0);
        hidari.add(jOpcion4, gridBagConstraints);

        jOpcion5.setText("Opcion 5");
        jOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 43, 0, 0);
        hidari.add(jOpcion5, gridBagConstraints);

        jOpcion6.setText("Opcion 6");
        jOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcion6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 43, 0, 0);
        hidari.add(jOpcion6, gridBagConstraints);

        jComboListHidari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboListHidari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboListHidariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        hidari.add(jComboListHidari, gridBagConstraints);

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 27, 0, 0);
        hidari.add(jSpinner1, gridBagConstraints);

        jDesliz.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDeslizStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 32, 0, 0);
        hidari.add(jDesliz, gridBagConstraints);

        migi.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel espejo"));
        migi.setLayout(new java.awt.GridBagLayout());

        Opciones1Migi.setText("Opciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 35, 0, 0);
        migi.add(Opciones1Migi, gridBagConstraints);

        jGrupoOpcionMigi.add(jOpcion1Migi);
        jOpcion1Migi.setText("Opcion 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 84, 0, 0);
        migi.add(jOpcion1Migi, gridBagConstraints);

        jGrupoOpcionMigi.add(jOpcion2Migi);
        jOpcion2Migi.setText("Opcion 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 84, 0, 0);
        migi.add(jOpcion2Migi, gridBagConstraints);

        jGrupoOpcionMigi.add(jOpcion3Migi);
        jOpcion3Migi.setText("Opcion 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 84, 0, 0);
        migi.add(jOpcion3Migi, gridBagConstraints);

        CorreoMigi.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 84, 0, 0);
        migi.add(CorreoMigi, gridBagConstraints);

        jContrasenyaMigi.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 84, 0, 0);
        migi.add(jContrasenyaMigi, gridBagConstraints);

        txtPassMigi.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 58, 0);
        migi.add(txtPassMigi, gridBagConstraints);

        txtCorreoMigi.setColumns(20);
        txtCorreoMigi.setText("sunombre@gmail.com...");
        txtCorreoMigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoMigiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 1, 0, 0);
        migi.add(txtCorreoMigi, gridBagConstraints);

        jOpcion6Migi.setText("Opcion 6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 43, 0, 0);
        migi.add(jOpcion6Migi, gridBagConstraints);

        jOpcion5Migi.setText("Opcion 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 43, 0, 0);
        migi.add(jOpcion5Migi, gridBagConstraints);

        jOpcion4Migi.setText("Opcion 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 43, 0, 0);
        migi.add(jOpcion4Migi, gridBagConstraints);

        txtMigi.setColumns(20);
        txtMigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMigiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        migi.add(txtMigi, gridBagConstraints);

        Texto1Migi.setText("Texto 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(79, 27, 0, 0);
        migi.add(Texto1Migi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 27, 0, 0);
        migi.add(jSpinnerMigi, gridBagConstraints);

        jComboListMigi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        migi.add(jComboListMigi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 32, 0, 0);
        migi.add(jDeslizMigi, gridBagConstraints);

        jAceptarMigi.setText("Aceptar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 32, 0, 0);
        migi.add(jAceptarMigi, gridBagConstraints);

        jRedondoMigi.setText("Redondo");
        jRedondoMigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRedondoMigiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 27, 0, 0);
        migi.add(jRedondoMigi, gridBagConstraints);

        jButtonAyudaMigi.setText("?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 17, 0, 36);
        migi.add(jButtonAyudaMigi, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hidari, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addComponent(migi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hidari, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(migi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHidari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHidari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHidari1ActionPerformed

    private void jRedondoHidari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRedondoHidari2ActionPerformed
        // TODO add your handling code here:
        jRedondoMigi.doClick();
    }//GEN-LAST:event_jRedondoHidari2ActionPerformed

    private void txtCorreoHidariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoHidariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoHidariActionPerformed

    private void txtCorreoMigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoMigiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMigiActionPerformed

    private void txtMigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMigiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMigiActionPerformed

    private void jRedondoMigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRedondoMigiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRedondoMigiActionPerformed

    private void txtHidari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHidari1KeyReleased
        // TODO add your handling code here:
        String txt = txtHidari1.getText();
        txtMigi.setText(txtInv(txt));
    }//GEN-LAST:event_txtHidari1KeyReleased

    private void txtCorreoHidariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoHidariKeyReleased
        // TODO add your handling code here:
        txtCorreoMigi.setText(txtCorreoHidari.getText());
    }//GEN-LAST:event_txtCorreoHidariKeyReleased

    private void txtPassHidariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassHidariKeyReleased
        // TODO add your handling code here:
        txtPassMigi.setText(new String(txtPassHidari.getPassword()));
    }//GEN-LAST:event_txtPassHidariKeyReleased

    private void jAceptarHidariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarHidariActionPerformed
        // TODO add your handling code here:
        jAceptarMigi.doClick();
    }//GEN-LAST:event_jAceptarHidariActionPerformed

    private void jButtonAyudaHidariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaHidariActionPerformed
        // TODO add your handling code here:
        jButtonAyudaMigi.doClick();
    }//GEN-LAST:event_jButtonAyudaHidariActionPerformed

    private void jOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion1ActionPerformed
        // TODO add your handling code here:
        jOpcion1Migi.setSelected(true);
    }//GEN-LAST:event_jOpcion1ActionPerformed

    private void jOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion2ActionPerformed
        // TODO add your handling code here:
        jOpcion2Migi.setSelected(true);
    }//GEN-LAST:event_jOpcion2ActionPerformed

    private void jOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion3ActionPerformed
        // TODO add your handling code here:
        jOpcion3Migi.setSelected(true);
    }//GEN-LAST:event_jOpcion3ActionPerformed

    private void jOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion4ActionPerformed
        // TODO add your handling code here:
        jOpcion4Migi.setSelected(jOpcion4.isSelected());
    }//GEN-LAST:event_jOpcion4ActionPerformed

    private void jOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion5ActionPerformed
        // TODO add your handling code here:
        jOpcion5Migi.setSelected(jOpcion5.isSelected());
    }//GEN-LAST:event_jOpcion5ActionPerformed

    private void jOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcion6ActionPerformed
        // TODO add your handling code here:
        jOpcion6Migi.setSelected(jOpcion6.isSelected());
    }//GEN-LAST:event_jOpcion6ActionPerformed

    private void jComboListHidariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboListHidariActionPerformed
        // TODO add your handling code here:
        jComboListMigi.setSelectedIndex(jComboListHidari.getSelectedIndex());
    }//GEN-LAST:event_jComboListHidariActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        jSpinnerMigi.setValue(jSpinner1.getValue());
        
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jDeslizStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDeslizStateChanged
        // TODO add your handling code here:
        jDeslizMigi.setValue(jDesliz.getValue());
    }//GEN-LAST:event_jDeslizStateChanged

    private String txtInv(String txt) {
        return new StringBuilder(txt).reverse().toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlatLaf().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorreoHidari;
    private javax.swing.JLabel CorreoMigi;
    private javax.swing.JLabel Opciones;
    private javax.swing.JLabel Opciones1Migi;
    private javax.swing.JLabel Texto1Hidari;
    private javax.swing.JLabel Texto1Migi;
    private javax.swing.JPanel hidari;
    private javax.swing.JButton jAceptarHidari;
    private javax.swing.JButton jAceptarMigi;
    private javax.swing.JButton jButtonAyudaHidari;
    private javax.swing.JButton jButtonAyudaMigi;
    private javax.swing.JComboBox<String> jComboListHidari;
    private javax.swing.JComboBox<String> jComboListMigi;
    private javax.swing.JLabel jContrasenyaHidari;
    private javax.swing.JLabel jContrasenyaMigi;
    private javax.swing.JSlider jDesliz;
    private javax.swing.JSlider jDeslizMigi;
    private javax.swing.ButtonGroup jGrupoOpcionHidari;
    private javax.swing.ButtonGroup jGrupoOpcionMigi;
    private javax.swing.JRadioButton jOpcion1;
    private javax.swing.JRadioButton jOpcion1Migi;
    private javax.swing.JRadioButton jOpcion2;
    private javax.swing.JRadioButton jOpcion2Migi;
    private javax.swing.JRadioButton jOpcion3;
    private javax.swing.JRadioButton jOpcion3Migi;
    private javax.swing.JCheckBox jOpcion4;
    private javax.swing.JCheckBox jOpcion4Migi;
    private javax.swing.JCheckBox jOpcion5;
    private javax.swing.JCheckBox jOpcion5Migi;
    private javax.swing.JCheckBox jOpcion6;
    private javax.swing.JCheckBox jOpcion6Migi;
    private javax.swing.JButton jRedondoHidari2;
    private javax.swing.JButton jRedondoMigi;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerMigi;
    private javax.swing.JPanel migi;
    private javax.swing.JTextField txtCorreoHidari;
    private javax.swing.JTextField txtCorreoMigi;
    private javax.swing.JTextField txtHidari1;
    private javax.swing.JTextField txtMigi;
    private javax.swing.JPasswordField txtPassHidari;
    private javax.swing.JPasswordField txtPassMigi;
    // End of variables declaration//GEN-END:variables
}
